// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/comment/proto/comment.proto

package comment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCommentsRequest struct {
	PostUid              string   `protobuf:"bytes,1,opt,name=postUid,proto3" json:"postUid,omitempty"`
	CommentUid           string   `protobuf:"bytes,2,opt,name=commentUid,proto3" json:"commentUid,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,4,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommentsRequest) Reset()         { *m = ListCommentsRequest{} }
func (m *ListCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentsRequest) ProtoMessage()    {}
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{0}
}
func (m *ListCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsRequest.Unmarshal(m, b)
}
func (m *ListCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsRequest.Marshal(b, m, deterministic)
}
func (dst *ListCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsRequest.Merge(dst, src)
}
func (m *ListCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentsRequest.Size(m)
}
func (m *ListCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsRequest proto.InternalMessageInfo

func (m *ListCommentsRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *ListCommentsRequest) GetCommentUid() string {
	if m != nil {
		return m.CommentUid
	}
	return ""
}

func (m *ListCommentsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCommentsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListCommentsResponse struct {
	Comments             []*SingleComment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	PageSize             int32            `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32            `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCommentsResponse) Reset()         { *m = ListCommentsResponse{} }
func (m *ListCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentsResponse) ProtoMessage()    {}
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{1}
}
func (m *ListCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsResponse.Unmarshal(m, b)
}
func (m *ListCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsResponse.Merge(dst, src)
}
func (m *ListCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentsResponse.Size(m)
}
func (m *ListCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsResponse proto.InternalMessageInfo

func (m *ListCommentsResponse) GetComments() []*SingleComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *ListCommentsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCommentsResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type SingleComment struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserUid              string               `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	PostUid              string               `protobuf:"bytes,3,opt,name=postUid,proto3" json:"postUid,omitempty"`
	Body                 string               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ParentUid            string               `protobuf:"bytes,5,opt,name=parentUid,proto3" json:"parentUid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	IsDeleted            bool                 `protobuf:"varint,8,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SingleComment) Reset()         { *m = SingleComment{} }
func (m *SingleComment) String() string { return proto.CompactTextString(m) }
func (*SingleComment) ProtoMessage()    {}
func (*SingleComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{2}
}
func (m *SingleComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleComment.Unmarshal(m, b)
}
func (m *SingleComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleComment.Marshal(b, m, deterministic)
}
func (dst *SingleComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleComment.Merge(dst, src)
}
func (m *SingleComment) XXX_Size() int {
	return xxx_messageInfo_SingleComment.Size(m)
}
func (m *SingleComment) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleComment.DiscardUnknown(m)
}

var xxx_messageInfo_SingleComment proto.InternalMessageInfo

func (m *SingleComment) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SingleComment) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *SingleComment) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *SingleComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SingleComment) GetParentUid() string {
	if m != nil {
		return m.ParentUid
	}
	return ""
}

func (m *SingleComment) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SingleComment) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

func (m *SingleComment) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type GetCommentRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentRequest) Reset()         { *m = GetCommentRequest{} }
func (m *GetCommentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentRequest) ProtoMessage()    {}
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{3}
}
func (m *GetCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentRequest.Unmarshal(m, b)
}
func (m *GetCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentRequest.Marshal(b, m, deterministic)
}
func (dst *GetCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentRequest.Merge(dst, src)
}
func (m *GetCommentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentRequest.Size(m)
}
func (m *GetCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentRequest proto.InternalMessageInfo

func (m *GetCommentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CreateCommentRequest struct {
	PostUid              string   `protobuf:"bytes,1,opt,name=postUid,proto3" json:"postUid,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ParentUid            string   `protobuf:"bytes,3,opt,name=parentUid,proto3" json:"parentUid,omitempty"`
	UserUid              string   `protobuf:"bytes,4,opt,name=userUid,proto3" json:"userUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{4}
}
func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(dst, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *CreateCommentRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateCommentRequest) GetParentUid() string {
	if m != nil {
		return m.ParentUid
	}
	return ""
}

func (m *CreateCommentRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type UpdateCommentRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCommentRequest) Reset()         { *m = UpdateCommentRequest{} }
func (m *UpdateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCommentRequest) ProtoMessage()    {}
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{5}
}
func (m *UpdateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCommentRequest.Unmarshal(m, b)
}
func (m *UpdateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCommentRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCommentRequest.Merge(dst, src)
}
func (m *UpdateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCommentRequest.Size(m)
}
func (m *UpdateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCommentRequest proto.InternalMessageInfo

func (m *UpdateCommentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateCommentRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateCommentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCommentResponse) Reset()         { *m = UpdateCommentResponse{} }
func (m *UpdateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCommentResponse) ProtoMessage()    {}
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{6}
}
func (m *UpdateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCommentResponse.Unmarshal(m, b)
}
func (m *UpdateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCommentResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCommentResponse.Merge(dst, src)
}
func (m *UpdateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCommentResponse.Size(m)
}
func (m *UpdateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCommentResponse proto.InternalMessageInfo

type RemoveContentRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContentRequest) Reset()         { *m = RemoveContentRequest{} }
func (m *RemoveContentRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveContentRequest) ProtoMessage()    {}
func (*RemoveContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{7}
}
func (m *RemoveContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContentRequest.Unmarshal(m, b)
}
func (m *RemoveContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContentRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContentRequest.Merge(dst, src)
}
func (m *RemoveContentRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveContentRequest.Size(m)
}
func (m *RemoveContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContentRequest proto.InternalMessageInfo

func (m *RemoveContentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RemoveContentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContentResponse) Reset()         { *m = RemoveContentResponse{} }
func (m *RemoveContentResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveContentResponse) ProtoMessage()    {}
func (*RemoveContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{8}
}
func (m *RemoveContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContentResponse.Unmarshal(m, b)
}
func (m *RemoveContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContentResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContentResponse.Merge(dst, src)
}
func (m *RemoveContentResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveContentResponse.Size(m)
}
func (m *RemoveContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContentResponse proto.InternalMessageInfo

type DeleteCommentRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentRequest) Reset()         { *m = DeleteCommentRequest{} }
func (m *DeleteCommentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentRequest) ProtoMessage()    {}
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{9}
}
func (m *DeleteCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentRequest.Unmarshal(m, b)
}
func (m *DeleteCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentRequest.Merge(dst, src)
}
func (m *DeleteCommentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentRequest.Size(m)
}
func (m *DeleteCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentRequest proto.InternalMessageInfo

func (m *DeleteCommentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeleteCommentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentResponse) Reset()         { *m = DeleteCommentResponse{} }
func (m *DeleteCommentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentResponse) ProtoMessage()    {}
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{10}
}
func (m *DeleteCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentResponse.Unmarshal(m, b)
}
func (m *DeleteCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentResponse.Merge(dst, src)
}
func (m *DeleteCommentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentResponse.Size(m)
}
func (m *DeleteCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentResponse proto.InternalMessageInfo

type GetOwnerRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerRequest) Reset()         { *m = GetOwnerRequest{} }
func (m *GetOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*GetOwnerRequest) ProtoMessage()    {}
func (*GetOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{11}
}
func (m *GetOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerRequest.Unmarshal(m, b)
}
func (m *GetOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerRequest.Marshal(b, m, deterministic)
}
func (dst *GetOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerRequest.Merge(dst, src)
}
func (m *GetOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_GetOwnerRequest.Size(m)
}
func (m *GetOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerRequest proto.InternalMessageInfo

func (m *GetOwnerRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetOwnerResponse struct {
	OwnerUid             string   `protobuf:"bytes,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerResponse) Reset()         { *m = GetOwnerResponse{} }
func (m *GetOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*GetOwnerResponse) ProtoMessage()    {}
func (*GetOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_comment_58f34ab1f7605aa0, []int{12}
}
func (m *GetOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerResponse.Unmarshal(m, b)
}
func (m *GetOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerResponse.Marshal(b, m, deterministic)
}
func (dst *GetOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerResponse.Merge(dst, src)
}
func (m *GetOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_GetOwnerResponse.Size(m)
}
func (m *GetOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerResponse proto.InternalMessageInfo

func (m *GetOwnerResponse) GetOwnerUid() string {
	if m != nil {
		return m.OwnerUid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCommentsRequest)(nil), "comment.ListCommentsRequest")
	proto.RegisterType((*ListCommentsResponse)(nil), "comment.ListCommentsResponse")
	proto.RegisterType((*SingleComment)(nil), "comment.SingleComment")
	proto.RegisterType((*GetCommentRequest)(nil), "comment.GetCommentRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "comment.CreateCommentRequest")
	proto.RegisterType((*UpdateCommentRequest)(nil), "comment.UpdateCommentRequest")
	proto.RegisterType((*UpdateCommentResponse)(nil), "comment.UpdateCommentResponse")
	proto.RegisterType((*RemoveContentRequest)(nil), "comment.RemoveContentRequest")
	proto.RegisterType((*RemoveContentResponse)(nil), "comment.RemoveContentResponse")
	proto.RegisterType((*DeleteCommentRequest)(nil), "comment.DeleteCommentRequest")
	proto.RegisterType((*DeleteCommentResponse)(nil), "comment.DeleteCommentResponse")
	proto.RegisterType((*GetOwnerRequest)(nil), "comment.GetOwnerRequest")
	proto.RegisterType((*GetOwnerResponse)(nil), "comment.GetOwnerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentClient interface {
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*SingleComment, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*SingleComment, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	RemoveContent(ctx context.Context, in *RemoveContentRequest, opts ...grpc.CallOption) (*RemoveContentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	GetOwner(ctx context.Context, in *GetOwnerRequest, opts ...grpc.CallOption) (*GetOwnerResponse, error)
}

type commentClient struct {
	cc *grpc.ClientConn
}

func NewCommentClient(cc *grpc.ClientConn) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*SingleComment, error) {
	out := new(SingleComment)
	err := c.cc.Invoke(ctx, "/comment.Comment/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*SingleComment, error) {
	out := new(SingleComment)
	err := c.cc.Invoke(ctx, "/comment.Comment/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/UpdateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) RemoveContent(ctx context.Context, in *RemoveContentRequest, opts ...grpc.CallOption) (*RemoveContentResponse, error) {
	out := new(RemoveContentResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/RemoveContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) GetOwner(ctx context.Context, in *GetOwnerRequest, opts ...grpc.CallOption) (*GetOwnerResponse, error) {
	out := new(GetOwnerResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/GetOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
type CommentServer interface {
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	GetComment(context.Context, *GetCommentRequest) (*SingleComment, error)
	CreateComment(context.Context, *CreateCommentRequest) (*SingleComment, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	RemoveContent(context.Context, *RemoveContentRequest) (*RemoveContentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	GetOwner(context.Context, *GetOwnerRequest) (*GetOwnerResponse, error)
}

func RegisterCommentServer(s *grpc.Server, srv CommentServer) {
	s.RegisterService(&_Comment_serviceDesc, srv)
}

func _Comment_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_RemoveContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).RemoveContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/RemoveContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).RemoveContent(ctx, req.(*RemoveContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_GetOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).GetOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/GetOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).GetOwner(ctx, req.(*GetOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comment.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComments",
			Handler:    _Comment_ListComments_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _Comment_GetComment_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _Comment_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _Comment_UpdateComment_Handler,
		},
		{
			MethodName: "RemoveContent",
			Handler:    _Comment_RemoveContent_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Comment_DeleteComment_Handler,
		},
		{
			MethodName: "GetOwner",
			Handler:    _Comment_GetOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/comment/proto/comment.proto",
}

func init() {
	proto.RegisterFile("pkg/comment/proto/comment.proto", fileDescriptor_comment_58f34ab1f7605aa0)
}

var fileDescriptor_comment_58f34ab1f7605aa0 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xe3, 0xb4, 0x71, 0xa6, 0x44, 0x94, 0x25, 0x25, 0xc6, 0x2a, 0xad, 0x65, 0x84, 0xe4,
	0x93, 0x23, 0x85, 0x0b, 0x42, 0x48, 0x80, 0x82, 0xe8, 0x01, 0x14, 0x24, 0x97, 0xfe, 0x80, 0xa4,
	0x9e, 0x5a, 0x16, 0xb1, 0xd7, 0x78, 0xd7, 0x20, 0x10, 0x67, 0x2e, 0x9c, 0x38, 0xf3, 0x67, 0x91,
	0x3f, 0xd6, 0x5e, 0x7f, 0xb5, 0x37, 0xcf, 0xce, 0xcc, 0x9b, 0xd9, 0xf7, 0xde, 0x1a, 0xce, 0xe3,
	0x2f, 0xfe, 0xf2, 0x9a, 0x86, 0x21, 0x46, 0x7c, 0x19, 0x27, 0x94, 0x53, 0x11, 0x39, 0x79, 0x44,
	0x26, 0x65, 0x68, 0x9c, 0xfb, 0x94, 0xfa, 0x7b, 0x2c, 0x8a, 0x76, 0xe9, 0xcd, 0x92, 0x07, 0x21,
	0x32, 0xbe, 0x0d, 0xe3, 0xa2, 0xd2, 0xfa, 0xa3, 0xc0, 0xc3, 0x8f, 0x01, 0xe3, 0xeb, 0xa2, 0x81,
	0xb9, 0xf8, 0x35, 0x45, 0xc6, 0x89, 0x0e, 0x93, 0x98, 0x32, 0x7e, 0x15, 0x78, 0xba, 0x62, 0x2a,
	0xf6, 0xd4, 0x15, 0x21, 0x39, 0x03, 0x28, 0xd1, 0xb3, 0xe4, 0x28, 0x4f, 0x4a, 0x27, 0xc4, 0x00,
	0x2d, 0xde, 0xfa, 0x78, 0x19, 0xfc, 0x44, 0x5d, 0x35, 0x15, 0xfb, 0xc0, 0xad, 0xe2, 0xac, 0x37,
	0xfb, 0xde, 0xa4, 0xe1, 0x0e, 0x13, 0x7d, 0x9c, 0x67, 0xa5, 0x13, 0xeb, 0xb7, 0x02, 0xf3, 0xe6,
	0x36, 0x2c, 0xa6, 0x11, 0x43, 0xb2, 0x02, 0xad, 0x1c, 0xc1, 0x74, 0xc5, 0x54, 0xed, 0xa3, 0xd5,
	0x23, 0x47, 0x5c, 0xf9, 0x32, 0x88, 0xfc, 0x3d, 0x96, 0x2d, 0x6e, 0x55, 0xd7, 0x58, 0x64, 0x74,
	0xeb, 0x22, 0x6a, 0x67, 0x91, 0x7f, 0x23, 0x98, 0x35, 0x70, 0xc9, 0x31, 0xa8, 0x69, 0x45, 0x46,
	0xf6, 0x99, 0x51, 0x94, 0x32, 0x4c, 0x6a, 0x16, 0x44, 0x28, 0x93, 0xa7, 0x36, 0xc9, 0x23, 0x30,
	0xde, 0x51, 0xef, 0x47, 0x7e, 0xf5, 0xa9, 0x9b, 0x7f, 0x93, 0x53, 0x98, 0xc6, 0xdb, 0xa4, 0xe4,
	0xf3, 0x20, 0x4f, 0xd4, 0x07, 0xe4, 0x05, 0x4c, 0xaf, 0x13, 0xdc, 0x72, 0xf4, 0xde, 0x72, 0xfd,
	0xd0, 0x54, 0xec, 0xa3, 0x95, 0xe1, 0x14, 0xaa, 0x3a, 0x42, 0x55, 0xe7, 0xb3, 0x50, 0xd5, 0xad,
	0x8b, 0xc9, 0x4b, 0x80, 0x90, 0x7a, 0xc1, 0x4d, 0x90, 0xb7, 0x4e, 0xee, 0x6c, 0x95, 0xaa, 0xb3,
	0x9d, 0x02, 0xf6, 0x0e, 0xf7, 0xc8, 0xd1, 0xd3, 0x35, 0x53, 0xb1, 0x35, 0xb7, 0x3e, 0xb0, 0x9e,
	0xc1, 0x83, 0x0b, 0x14, 0x22, 0x09, 0xc7, 0x74, 0x08, 0xb2, 0x7e, 0xc1, 0x7c, 0x9d, 0x6f, 0xd3,
	0xaa, 0x1c, 0xf6, 0x96, 0xa0, 0x67, 0x34, 0x44, 0x8f, 0xda, 0xa6, 0x47, 0x12, 0x61, 0xdc, 0x10,
	0xc1, 0x7a, 0x05, 0xf3, 0xab, 0xd8, 0xeb, 0x4e, 0xef, 0x0a, 0xd9, 0x33, 0xd5, 0x5a, 0xc0, 0x49,
	0xab, 0xbb, 0x70, 0xa2, 0x65, 0xc3, 0xdc, 0xc5, 0x90, 0x7e, 0xc3, 0x35, 0x8d, 0xf8, 0xad, 0xd7,
	0x5f, 0xc0, 0x49, 0xab, 0xb2, 0x86, 0x28, 0x98, 0xbc, 0x93, 0xc1, 0x05, 0x9c, 0xb4, 0x2a, 0x4b,
	0x88, 0xa7, 0x70, 0xff, 0x02, 0xf9, 0xa7, 0xef, 0x11, 0x26, 0xc3, 0xdd, 0x0e, 0x1c, 0xd7, 0x45,
	0xe5, 0x43, 0x32, 0x40, 0xa3, 0xd9, 0x41, 0x4d, 0x7e, 0x15, 0xaf, 0xfe, 0x8e, 0x61, 0x22, 0xec,
	0xfe, 0x01, 0xee, 0xc9, 0x0f, 0x91, 0x9c, 0x56, 0xcf, 0xad, 0xe7, 0x6f, 0x61, 0x3c, 0x19, 0xc8,
	0x96, 0x43, 0xdf, 0x00, 0xd4, 0x7e, 0x21, 0x46, 0x55, 0xdc, 0x31, 0x91, 0x31, 0xf0, 0xaa, 0xc9,
	0x7b, 0x98, 0x35, 0xac, 0x44, 0xea, 0x89, 0x7d, 0x16, 0x1b, 0xc4, 0xd9, 0xc0, 0xac, 0x21, 0xab,
	0x84, 0xd3, 0x67, 0x16, 0xe3, 0x6c, 0x28, 0x5d, 0xde, 0x6c, 0x03, 0xb3, 0x86, 0xc6, 0x12, 0x5e,
	0x9f, 0x4b, 0x24, 0xbc, 0x5e, 0x6b, 0x64, 0x78, 0x0d, 0xc1, 0x25, 0xbc, 0x3e, 0xcb, 0x48, 0x78,
	0xbd, 0x3e, 0x21, 0xaf, 0x41, 0x13, 0x16, 0x20, 0xba, 0xcc, 0xbb, 0x6c, 0x1d, 0xe3, 0x71, 0x4f,
	0xa6, 0x00, 0xd8, 0x1d, 0xe6, 0x3f, 0x8a, 0xe7, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x46, 0x9b,
	0xee, 0x34, 0x73, 0x06, 0x00, 0x00,
}
